
ROGUEFOCUS			= "连击点助手";
ROGUEFOCUS_WELCOME	= "连击点助手已加载";

ROGUEFOCUS_ENERGY	= "2S 回能";
ROGUEFOCUS_SCALE	= "缩放";
ROGUEFOCUS_LOW		= "小";
ROGUEFOCUS_HIGH		= "大";
ROGUEFOCUS_COMBAT	= "战斗中显示";
ROGUEFOCUS_STEALTH	= "潜行中显示";
ROGUEFOCUS_OTHER	= "总是显示";
ROGUEFOCUS_SOUND	= "2S回能提示音";
ROGUEFOCUS_LOCK		= "锁定位置";
ROGUEFOCUS_MOVE		= "提示：解锁后可移动"
