
EL_Types = {
	[1] = "友好的",
	[2] = "仇恨的",
	[3] = "快乐的",
	[4] = "无聊的",
	[5] = "伤心的",
	[7] = "嘲弄",
	[8] = "感情",
	[9] = "问候",
	[10] = "战斗",
	[11] = "自贬",
	[12] = "反应",
	[13] = "其他",
}

EL_React = {
	[0] = "",
	[1] = "A",
	[2] = "V",
	[3] = "AV",
}

-- CUSTOM EMOTE VARIABLES: <Target>, <He>, <His>, <he>, <his>
-- The text for custom emotes should NOT contain the player's name at the beginning. It will be sent with a /e preceeding it.
-- NOTE: They MUST start with category 6, no matter how many other categories are added.

EL_Emotes = {
	["amaze"] = {
		["types"] = {12},
		["none"] = "你感到很惊奇！",
		["target"] = "<Target>让你感到很惊奇！",
		["react"] = 0,
	},
	["angry"] = {
		["types"] = {2},
		["none"] = "你愤怒地挥起拳头。",
		["target"] = "你向<Target>愤怒地挥起拳头。",
		["react"] = 1,
	},
	["apologize"] = {
		["types"] = {11},
		["none"] = "你向大家表示道歉。对不起！",
		["target"] = "你向<Target>表示道歉。对不起！",
		["react"] = 0,
	},
	["applaud"] = {
		["types"] = {1},
		["none"] = "你大声喝彩。好！",
		["target"] = "你向<Target>大声喝彩。真棒！",
		["react"] = 3,
	},
	["攻击目标"] = {
		["types"] = {10},
		["none"] = "你告诉所有人进攻某物。",
		["target"] = "你要所有人进攻<Target>。",
		["react"] = 3,
	},
	["bark"] = {
		["types"] = {2},
		["none"] = "你仰天长啸。呜……！",
		["target"] = "你对着<Target>咆哮。",
		["react"] = 0,
	},
	["bashful"] = {
		["types"] = {8},
		["none"] = "你非常害羞。",
		["target"] = "你太害羞了……从而无法引起<Target>的注意。",
		["react"] = 1,
	},
	["beckon"] = {
		["types"] = {9},
		["none"] = "你招手示意大家都过去。",
		["target"] = "你招手示意<Target>过来。",
		["react"] = 0,
	},
	["beg"] = {
		["types"] = {11},
		["none"] = "你向周围的人祈求。真可怜。",
		["target"] = "你在祈求<Target>。好可怜啊。",
		["react"] = 1,
	},
	["belch"] = {
		["types"] = {7},
		["none"] = "你打了个响亮的嗝。",
		["target"] = "你很没有礼貌得对着<Target>打了个嗝。",
		["react"] = 0,
	},
	["bite"] = {
		["types"] = {2},
		["none"] = "你四下张望，想找个人咬一口。",
		["target"] = "你咬了<Target>一口。啊！",
		["react"] = 0,
	},
	["bleed"] = {
		["types"] = {13},
		["none"] = "你的伤口渗出了鲜血。",
		["target"] = "你的伤口渗出了鲜血。",
		["react"] = 0,
	},
	["blink"] = {
		["types"] = {12},
		["none"] = "你眨了眨眼。",
		["target"] = "你对<Target>眨了眨眼。",
		["react"] = 0,
	},
	["blush"] = {
		["types"] = {8},
		["none"] = "你脸红了。",
		["target"] = "你对着<Target>脸红了。",
		["react"] = 1,
	},
	["boggle"] = {
		["types"] = {12},
		["none"] = "你对这个状况不置可否。",
		["target"] = "你对<Target>不置可否。",
		["react"] = 1,
	},
	["bonk"] = {
		["types"] = {12},
		["none"] = "你重重的敲了一下你的脑袋，发出“咚”的一声。",
		["target"] = "你重重的敲了一下<Target>的脑袋，发出“咚”的一声。",
		["react"] = 0,
	},
	["bored"] = {
		["types"] = {5},
		["none"] = "你已经对这种苦差事不胜其烦了！",
		["target"] = "你对<Target>感到十分厌烦。",
		["react"] = 2,
	},
	["bounce"] = {
		["types"] = {3},
		["none"] = "你上蹿下跳。",
		["target"] = "你在<Target>面前上窜下跳。",
		["react"] = 0,
	},
	["bow"] = {
		["types"] = {9},
		["none"] = "你优雅的鞠了一躬。",
		["target"] = "你向<Target>鞠躬。",
		["react"] = 1,
	},
	["cackle"] = {
		["types"] = {3},
		["none"] = "你见此情景咯咯的笑个不停。",
		["target"] = "你对着<Target>咯咯的笑个不停。",
		["react"] = 3,
	},
	["calm"] = {
		["types"] = {12},
		["none"] = "你保持冷静。",
		["target"] = "你试图让<Target>冷静下来。",
		["react"] = 0,
	},
	["cheer"] = {
		["types"] = {1},
		["none"] = "你大声欢呼。",
		["target"] = "你为<Target>欢呼。",
		["react"] = 3,
	},
	["chicken"] = {
		["types"] = {3},
		["none"] = "你像母鸡一样扇动着双臂绕着圈子咯咯咯地叫！",
		["target"] = "你扇动着双臂绕着<Target>咯咯咯的叫！",
		["react"] = 3,
	},
	["chuckle"] = {
		["types"] = {3},
		["none"] = "你吃吃地笑着。",
		["target"] = "你对着<Target>吃吃地笑。",
		["react"] = 3,
	},
	["clap"] = {
		["types"] = {1},
		["none"] = "你激动地鼓掌。",
		["target"] = "你激动地为<Target>鼓掌。",
		["react"] = 3,
	},
	["cold"] = {
		["types"] = {5},
		["none"] = "你告诉大家你感到很冷。",
		["target"] = "你告诉<Target>你感到很冷。",
		["react"] = 0,
	},
	["comfort"] = {
		["types"] = {5},
		["none"] = "你需要安慰。",
		["target"] = "你安慰<Target>。",
		["react"] = 0,
	},
	["confused"] = {
		["types"] = {12},
		["none"] = "你被完全搞糊涂了。",
		["target"] = "你疑惑地看着<Target>。",
		["react"] = 1,
	},
	["congrats"] = {
		["types"] = {9},
		["none"] = "你向你周围大家表示祝贺。",
		["target"] = "你向<Target>表示祝贺。",
		["react"] = 3,
	},
	["cough"] = {
		["types"] = {13},
		["none"] = "你干咳了几下。",
		["target"] = "你对着<Target>咳嗽了几下。",
		["react"] = 0,
	},
	["cower"] = {
		["types"] = {11},
		["none"] = "你害怕地退缩了。",
		["target"] = "你一看到<Target>就害怕地退缩了。",
		["react"] = 0,
	},
	["crack"] = {
		["types"] = {2},
		["none"] = "你把手上的关节捏的咯咯作声。",
		["target"] = "你把手上的关节捏的咯咯作声，直直的望着<Target>。",
		["react"] = 0,
	},
	["cringe"] = {
		["types"] = {11},
		["none"] = "你因为恐惧而退缩了。",
		["target"] = "你在<Target>的面前退缩了。",
		["react"] = 0,
	},
	["cry"] = {
		["types"] = {5},
		["none"] = "你哭了。",
		["target"] = "你扑在<Target>的肩膀上泣不成声。",
		["react"] = 3,
	},
	["cuddle"] = {
		["types"] = {8},
		["none"] = "你想要被拥抱一下。",
		["target"] = "你靠着<Target>睡去。",
		["react"] = 0,
	},
	["curious"] = {
		["types"] = {12},
		["none"] = "你对周围的人流露出好奇心。",
		["target"] = "你对于<Target>能胜任什么工作很感兴趣。",
		["react"] = 1,
	},
	["curtsey"] = {
		["types"] = {9},
		["none"] = "你行了个屈膝礼。",
		["target"] = "你向<Target>行屈膝礼。",
		["react"] = 1,
	},
	["dance"] = {
		["types"] = {1},
		["none"] = "你开始跳舞。",
		["target"] = "你在和<Target>跳舞。",
		["react"] = 1,
	},
	["doom"] = {
		["types"] = {2},
		["none"] = "你怒不可遏地威胁大家。",
		["target"] = "你怒不可遏地威胁<Target>。",
		["react"] = 0,
	},
	["drink"] = {
		["types"] = {1},
		["none"] = "你举起酒杯，然后一饮而尽。干杯！",
		["target"] = "你向<Target>举杯。干杯！",
		["react"] = 1,
	},
	["drool"] = {
		["types"] = {13},
		["none"] = "一条长长的口水挂在你的嘴边。",
		["target"] = "你看着<Target>流出了口水。",
		["react"] = 0,
	},
	["duck"] = {
		["types"] = {12},
		["none"] = "你蹲着藏了起来。",
		["target"] = "你紧紧地跟在<Target>后面。",
		["react"] = 0,
	},
	["eat"] = {
		["types"] = {4},
		["none"] = "你开始吃东西。",
		["target"] = "你在<Target>面前开始吃东西。",
		["react"] = 1,
	},
	["excited"] = {
		["types"] = {1},
		["none"] = "你正和大家兴高采烈地交谈着。",
		["target"] = "你正和<Target>兴高采烈地交谈着。",
		["react"] = 1,
	},
	["eye"] = {
		["types"] = {13},
		["none"] = "你眯起了眼睛。",
		["target"] = "你上下打量了一下<Target>。",
		["react"] = 0,
	},
	["fart"] = {
		["types"] = {7},
		["none"] = "你放了一个很响的屁。嗯…什么东西这么臭？",
		["target"] = "你靠近<Target>然后放了一个很响的屁。",
		["react"] = 0,
	},
	["fidget"] = {
		["types"] = {12},
		["none"] = "你显得坐立不安。",
		["target"] = "你等<Target>等得坐立不安。",
		["react"] = 0,
	},
	["逃跑"] = {
		["types"] = {10},
		["none"] = "你叫所有人快跑。",
		["target"] = "你叫所有人快跑。",
		["react"] = 3,
	},
	["flex"] = {
		["types"] = {4},
		["none"] = "你正在展示你的肌肉。哇，好壮啊！",
		["target"] = "你向<Target>展示你的肌肉。哇，好强啊！",
		["react"] = 1,
	},
	["调情"] = {
		["types"] = {8},
		["none"] = "你调情。",
		["target"] = "你对<Target>调情。",
		["react"] = 3,
	},
	["flop"] = {
		["types"] = {11},
		["none"] = "你无助地走来走去。",
		["target"] = "你无助地在<Target>旁边走来走去。",
		["react"] = 0,
	},
	["跟着我"] = {
		["types"] = {10},
		["none"] = "你示意所有人跟着。",
		["target"] = "你示意<Target>跟着。",
		["react"] = 3,
	},
	["frown"] = {
		["types"] = {5},
		["none"] = "你皱着眉头。",
		["target"] = "你失望地对<Target>皱起了眉头。",
		["react"] = 0,
	},
	["gaze"] = {
		["types"] = {13},
		["none"] = "你凝视着远方。",
		["target"] = "你殷切地注视着<Target>。",
		["react"] = 0,
	},
	["giggle"] = {
		["types"] = {3},
		["none"] = "你在咯咯地傻笑。",
		["target"] = "你对着<Target>咯咯地傻笑。",
		["react"] = 3,
	},
	["glare"] = {
		["types"] = {2},
		["none"] = "你生气地瞪大了眼睛。",
		["target"] = "你生气地对着<Target>瞪大了眼睛。",
		["react"] = 0,
	},
	["gloat"] = {
		["types"] = {7},
		["none"] = "你幸灾乐祸于大家的不幸。",
		["target"] = "你幸灾乐祸于<Target>的不幸。",
		["react"] = 3,
	},
	["golfclap"] = {
		["types"] = {7},
		["none"] = "你心不在焉的鼓掌，明显不太在意。",
		["target"] = "你为<Target>鼓掌，但明显不太在意。",
		["react"] = 3,
	},
	["goodbye"] = {
		["types"] = {1},
		["none"] = "你向大家挥手告别。再见！",
		["target"] = "你向<Target>挥手告别。再见！",
		["react"] = 3,
	},
	["greet"] = {
		["types"] = {9},
		["none"] = "你热情地问候和大家。",
		["target"] = "你热情问候<Target>。",
		["react"] = 1,
	},
	["grin"] = {
		["types"] = {3},
		["none"] = "你顽皮地笑了笑。",
		["target"] = "你顽皮地对<Target>一笑。",
		["react"] = 0,
	},
	["groan"] = {
		["types"] = {5},
		["none"] = "你开始呻吟。",
		["target"] = "你对着<Target>呻吟。",
		["react"] = 0,
	},
	["grovel"] = {
		["types"] = {11},
		["none"] = "你卑微地跪在地上。",
		["target"] = "你在<Target>面前卑躬屈膝，好像一个屈从的苦工一样。",
		["react"] = 1,
	},
	["growl"] = {
		["types"] = {2},
		["none"] = "你在高声怒吼。",
		["target"] = "你对着<Target>高声怒吼。",
		["react"] = 1,
	},
	["guffaw"] = {
		["types"] = {3},
		["none"] = "你放声大笑。",
		["target"] = "你看了<Target>一眼然后哈哈大笑。",
		["react"] = 3,
	},
	["hail"] = {
		["types"] = {9},
		["none"] = "你和周围所有的人打招呼。",
		["target"] = "你和<Target>打招呼。",
		["react"] = 1,
	},
	["happy"] = {
		["types"] = {3},
		["none"] = "你显得非常高兴！",
		["target"] = "你感到和<Target>在一起很开心！",
		["react"] = 0,
	},
	["治疗我"] = {
		["types"] = {10},
		["none"] = "你大声请求治疗！",
		["target"] = "你大声请求治疗！",
		["react"] = 3,
	},
	["hello"] = {
		["types"] = {9},
		["none"] = "你真心地向大家表示问候。",
		["target"] = "你真心地向<Target>表示问候。",
		["react"] = 3,
	},
	["呼救"] = {
		["types"] = {10},
		["none"] = "你大声呼救！",
		["target"] = "你大声呼救！",
		["react"] = 3,
	},
	["hug"] = {
		["types"] = {8},
		["none"] = "你需要一个拥抱！",
		["target"] = "你拥抱了<Target>。",
		["react"] = 0,
	},
	["hungry"] = {
		["types"] = {4},
		["none"] = "你感到很饿！",
		["target"] = "你感到很饿。也许在<Target>那里可以找到一些食物。",
		["react"] = 0,
	},
	["敌人"] = {
		["types"] = {10},
		["none"] = "你大叫敌人来了！",
		["target"] = "你大叫敌人来了！",
		["react"] = 3,
	},
	["insult"] = {
		["types"] = {7},
		["none"] = "你觉得你身边的人都是没有教养的家伙。",
		["target"] = "你认为<Target>是个没教养的家伙。",
		["react"] = 1,
	},
	["introduce"] = {
		["types"] = {1},
		["none"] = "你向大家介绍你自己。",
		["target"] = "你向<Target>作了一番自我介绍。",
		["react"] = 0,
	},
	["jk"] = {
		["types"] = {13},
		["none"] = "你只是在开玩笑。",
		["target"] = "你告诉<Target>你只是在开玩笑。",
		["react"] = 0,
	},
	["kiss"] = {
		["types"] = {8},
		["none"] = "你抛出一个飞吻。",
		["target"] = "你给了<Target>一个飞吻。",
		["react"] = 3,
	},
	["laugh"] = {
		["types"] = {3},
		["none"] = "你大笑。",
		["target"] = "你在嘲笑<Target>。",
		["react"] = 3,
	},
	["lavish"] = {
		["types"] = {1},
		["none"] = "你赞美光明的力量。",
		["target"] = "你对于<Target>大加赞赏。",
		["react"] = 0,
	},
	["lay"] = {
		["types"] = {4},
		["none"] = "你躺了下来。",
		["target"] = "你在<Target>面前躺下。",
		["react"] = 1,
	},
	["lick"] = {
		["types"] = {8},
		["none"] = "你舔了舔嘴唇。",
		["target"] = "你舔了舔<Target>。",
		["react"] = 0,
	},
	["listen"] = {
		["types"] = {1},
		["none"] = "你正在仔细地聆听！",
		["target"] = "你认真地听<Target>说话。",
		["react"] = 0,
	},
	["lost"] = {
		["types"] = {5},
		["none"] = "你彻底地失败了。",
		["target"] = "你告诉<Target>你已经彻底失败了。",
		["react"] = 1,
	},
	["love"] = {
		["types"] = {8},
		["none"] = "你感受到了深深的爱意。",
		["target"] = "你爱<Target>。",
		["react"] = 0,
	},
	["massage"] = {
		["types"] = {8},
		["none"] = "你需要按摩一下！",
		["target"] = "你帮<Target>按摩肩膀。",
		["react"] = 0,
	},
	["moan"] = {
		["types"] = {8},
		["none"] = "你轻轻地呻吟。",
		["target"] = "你对着<Target>轻轻地呻吟。",
		["react"] = 0,
	},
	["mock"] = {
		["types"] = {5},
		["none"] = "你看破红尘，觉得一切都无所谓了。",
		["target"] = "你嘲笑<Target>的愚蠢。",
		["react"] = 0,
	},
	["moo"] = {
		["types"] = {9},
		["none"] = "哞~~~",
		["target"] = "你对<Target>发出牛叫声。哞~~~",
		["react"] = 0,
	},
	["moon"] = {
		["types"] = {7},
		["none"] = "你把屁股对着大家。",
		["target"] = "你把屁股对着<Target>。",
		["react"] = 0,
	},
	["mourn"] = {
		["types"] = {5},
		["none"] = "你深深的陷入对于死者的哀思中。",
		["target"] = "你深深的陷入对于<Target>之死的哀思中。",
		["react"] = 3,
	},
	["no"] = {
		["types"] = {12},
		["none"] = "你斩钉截铁地说了个不字。",
		["target"] = "你坚决地对<Target>说不。",
		["react"] = 3,
	},
	["nod"] = {
		["types"] = {12},
		["none"] = "你点了点头。",
		["target"] = "你对<Target>点了点头。",
		["react"] = 3,
	},
	["nosepick"] = {
		["types"] = {7},
		["none"] = "你无聊地挖鼻孔来打发时间。",
		["target"] = "你挖了挖鼻孔，把手指伸到<Target>面前。",
		["react"] = 0,
	},
	["魔法耗尽"] = {
		["types"] = {10},
		["none"] = "你宣布你的法力不足！",
		["target"] = "你宣布你的法力不足！",
		["react"] = 3,
	},
	["开火"] = {
		["types"] = {10},
		["none"] = "你命令开火！",
		["target"] = "你命令开火！",
		["react"] = 3,
	},
	["panic"] = {
		["types"] = {11},
		["none"] = "你惊恐地跑来跑去。",
		["target"] = "你看了<Target>一眼然后大惊失色。",
		["react"] = 0,
	},
	["pat"] = {
		["types"] = {8},
		["none"] = "你需要一些安慰。",
		["target"] = "你轻轻拍了拍<Target>。",
		["react"] = 0,
	},
	["peer"] = {
		["types"] = {4},
		["none"] = "你仔细地打量了一下四周。",
		["target"] = "你仔细地打量了一下<Target>。",
		["react"] = 0,
	},
	["pity"] = {
		["types"] = {7},
		["none"] = "你对你周围的人表示同情。",
		["target"] = "你轻蔑地看着<Target>这个可怜的家伙。",
		["react"] = 0,
	},
	["point"] = {
		["types"] = {4},
		["none"] = "你指向远方。",
		["target"] = "你指着<Target>。",
		["react"] = 1,
	},
	["poke"] = {
		["types"] = {4},
		["none"] = "你戳了戳你的肚子然后咯咯地傻笑。",
		["target"] = "你戳了戳<Target>说：“嗨！”",
		["react"] = 0,
	},
	["ponder"] = {
		["types"] = {12},
		["none"] = "你仔细斟酌着当前的状况。",
		["target"] = "你对<Target>的行为认真的思考着。",
		["react"] = 1,
	},
	["pounce"] = {
		["types"] = {8},
		["none"] = "你从暗处扑了出来。",
		["target"] = "你向着<Target>扑了过去。",
		["react"] = 0,
	},
	["pray"] = {
		["types"] = {4},
		["none"] = "你虔诚地向神祈祷。",
		["target"] = "你虔诚地为<Target>祈祷。",
		["react"] = 1,
	},
	["purr"] = {
		["types"] = {8},
		["none"] = "你像猫一样发出咕噜声。",
		["target"] = "你对着<Target>发出咕噜声。",
		["react"] = 0,
	},
	["puzzled"] = {
		["types"] = {12},
		["none"] = "你被搞糊涂了。这到底是怎么一回事啊？",
		["target"] = "你被<Target>搞糊涂了。",
		["react"] = 1,
	},
	["question"] = {
		["types"] = {4},
		["none"] = "你想要知道生活的意义。",
		["target"] = "你向<Target>提问。",
		["react"] = 1,
	},
	["raise"] = {
		["types"] = {13},
		["none"] = "你举起了你的手。",
		["target"] = "你看着<Target>举起了你的手。",
		["react"] = 0,
	},
	["ready"] = {
		["types"] = {1},
		["none"] = "你告诉大家你已经准备好了！",
		["target"] = "你告诉<Target>你已经准备好了。",
		["react"] = 0,
	},
	["rear"] = {
		["types"] = {7},
		["none"] = "你扭了扭屁股。",
		["target"] = "你对着<Target>扭了扭屁股。",
		["react"] = 0,
	},
	["roar"] = {
		["types"] = {2},
		["none"] = "你发出野兽般的狂吼。好凶啊！",
		["target"] = "你对着<Target>发出野兽般的狂吼。好可怕啊！ ",
		["react"] = 1,
	},
	["rofl"] = {
		["types"] = {3},
		["none"] = "你笑翻在地。",
		["target"] = "你对着<Target>笑翻在地。",
		["react"] = 3,
	},
	["rude"] = {
		["types"] = {7},
		["none"] = "你做了个粗鲁的手势。",
		["target"] = "你对<Target>做了个粗鲁的手势。",
		["react"] = 1,
	},
	["salute"] = {
		["types"] = {9},
		["none"] = "你立正敬礼。",
		["target"] = "你满怀敬意地向<Target>致礼。",
		["react"] = 1,
	},
	["scared"] = {
		["types"] = {11},
		["none"] = "你看上去十分惊恐不安。",
		["target"] = "你非常害怕<Target>。",
		["react"] = 0,
	},
	["scratch"] = {
		["types"] = {13},
		["none"] = "你在帮你自己搔痒。啊，舒服多了！",
		["target"] = "你在帮<Target>搔痒。好可爱啊！",
		["react"] = 0,
	},
	["sexy"] = {
		["types"] = {8},
		["none"] = "你的装束实在是太有诱惑力了……让人怦然心动。",
		["target"] = "你觉得<Target>真实魅力十足。",
		["react"] = 0,
	},
	["shimmy"] = {
		["types"] = {13},
		["none"] = "你在众人面前舞动。",
		["target"] = "你在<Target>面前舞动。",
		["react"] = 0,
	},
	["shiver"] = {
		["types"] = {5},
		["none"] = "你冷得不断颤抖。",
		["target"] = "你靠着<Target>冷得不断颤抖。",
		["react"] = 0,
	},
	["shoo"] = {
		["types"] = {2},
		["none"] = "你发出嘘声让那些讨厌的家伙走开。",
		["target"] = "你嘘走了<Target>。走开，讨厌的家伙！",
		["react"] = 0,
	},
	["shrug"] = {
		["types"] = {12},
		["none"] = "你耸了耸肩说：“天知道。”",
		["target"] = "你对着<Target>耸了耸肩说：“天知道。”",
		["react"] = 1,
	},
	["shy"] = {
		["types"] = {8},
		["none"] = "你显得十分害羞。",
		["target"] = "你在<Target>面前感到很害羞。",
		["react"] = 1,
	},
	["sigh"] = {
		["types"] = {5},
		["none"] = "你长长地叹了一口气。",
		["target"] = "你对着<Target>叹了口气。",
		["react"] = 2,
	},
	["笑话"] = {
		["types"] = {3},
		["none"] = "你讲了一个笑话。",
		["target"] = "你给<Target>讲了一个笑话。",
		["react"] = 3,
	},
	["slap"] = {
		["types"] = {4},
		["none"] = "你扇了自己一个耳光，啊！",
		["target"] = "你扇了<Target>一个耳光，啊！",
		["react"] = 0,
	},
	["sleep"] = {
		["types"] = {4},
		["none"] = "你进入了梦乡。Zzzzzzz…",
		["target"] = "你进入了梦乡。Zzzzzzz…",
		["react"] = 1,
	},
	["smell"] = {
		["types"] = {7},
		["none"] = "你闻了闻周围的空气。Wow，有些人好臭啊！",
		["target"] = "你把鼻子凑过来闻了闻<Target>。哇哦，你好臭啊！",
		["react"] = 0,
	},
	["smile"] = {
		["types"] = {3},
		["none"] = "你露出了微笑。",
		["target"] = "你对<Target>露出了微笑。",
		["react"] = 0,
	},
	["smirk"] = {
		["types"] = {3},
		["none"] = "你的脸上渐渐的露出了顽皮的傻笑。",
		["target"] = "你顽皮的对着<Target>傻笑。",
		["react"] = 0,
	},
	["snarl"] = {
		["types"] = {2},
		["none"] = "你呲牙咧嘴地开始怒吼。",
		["target"] = "你呲牙咧嘴地朝着<Target>怒吼。",
		["react"] = 0,
	},
	["snicker"] = {
		["types"] = {3},
		["none"] = "你暗自偷笑。",
		["target"] = "你对着<Target>窃笑。",
		["react"] = 0,
	},
	["sniff"] = {
		["types"] = {12},
		["none"] = "你嗅了嗅周围的空气。",
		["target"] = "你仔细的嗅了嗅<Target>。",
		["react"] = 0,
	},
	["snub"] = {
		["types"] = {2},
		["none"] = "你大声训斥着周围卑贱的苦工。",
		["target"] = "你对<Target>十分冷淡。",
		["react"] = 0,
	},
	["soothe"] = {
		["types"] = {8},
		["none"] = "你需要安慰。",
		["target"] = "你安抚着<Target>。一切……一切都会好的。",
		["react"] = 0,
	},
	["spit"] = {
		["types"] = {2},
		["none"] = "你朝地上吐口水。",
		["target"] = "你对着<Target>吐口水。",
		["react"] = 0,
	},
	["stare"] = {
		["types"] = {4},
		["none"] = "你凝视着远方。",
		["target"] = "你用目光压倒了<Target>。",
		["react"] = 0,
	},
	["surprised"] = {
		["types"] = {12},
		["none"] = "你感到非常的惊讶！",
		["target"] = "你对于<Target>的行为感到很惊讶。",
		["react"] = 0,
	},
	["surrender"] = {
		["types"] = {4},
		["none"] = "你向对手投降。",
		["target"] = "你向<Target>投降。失败的滋味真不好受啊…",
		["react"] = 1,
	},
	["tap"] = {
		["types"] = {12},
		["none"] = "你不耐烦地用脚打着拍子，快一点!",
		["target"] = "你一边用脚打着拍子一边等待<Target>。",
		["react"] = 0,
	},
	["taunt"] = {
		["types"] = {7},
		["none"] = "你对周围的人做了个嘲弄的姿势。记住了！笨蛋！",
		["target"] = "你对<Target>做了个嘲弄的姿势。记住了！",
		["react"] = 3,
	},
	["tease"] = {
		["types"] = {7},
		["none"] = "你真是个喜欢嘲弄别人的家伙。",
		["target"] = "你嘲弄了<Target>一番。",
		["react"] = 0,
	},
	["thank"] = {
		["types"] = {1},
		["none"] = "你向周围的大家表示感谢。",
		["target"] = "你对<Target>表示感谢。",
		["react"] = 3,
	},
	["thirsty"] = {
		["types"] = {13},
		["none"] = "你感到非常的口渴。有没有人能给点喝的？",
		["target"] = "你告诉<Target>你很渴。朋友，有没有可以喝的？",
		["react"] = 0,
	},
	["tickle"] = {
		["types"] = {8},
		["none"] = "你想要被挠挠胳肢窝。嘿嘿！",
		["target"] = "你在挠<Target>的胳肢窝。嘿嘿！",
		["react"] = 0,
	},
	["veto"] = {
		["types"] = {13},
		["none"] = "你极力反对这样的行为。",
		["target"] = "你反对<Target>这样做。",
		["react"] = 0,
	},
	["violin"] = {
		["types"] = {5},
		["none"] = "你小声地哭了起来。",
		["target"] = "你在<Target>面前小声地哭了起来。",
		["react"] = 3,
	},
	["等等"] = {
		["types"] = {10},
		["none"] = "你要所有人等着。",
		["target"] = "你要<Target>等着。",
		["react"] = 3,
	},
	["wave"] = {
		["types"] = {1},
		["none"] = "你挥了挥手。",
		["target"] = "你向<Target>挥手致意。",
		["react"] = 0,
	},
	["welcome"] = {
		["types"] = {9},
		["none"] = "你向大家表示欢迎。",
		["target"] = "你欢迎<Target>的到来。",
		["react"] = 3,
	},
	["whine"] = {
		["types"] = {11},
		["none"] = "你在可怜巴巴地诉苦。",
		["target"] = "你可怜巴巴地向<Target>诉苦。",
		["react"] = 0,
	},
	["whistle"] = {
		["types"] = {1},
		["none"] = "你响亮地吹了一声口哨。",
		["target"] = "你对着<Target>吹了一声口哨。",
		["react"] = 2,
	},
	["wink"] = {
		["types"] = {8},
		["none"] = "你眨神秘地了眨眼。",
		["target"] = "你神秘地朝<Target>眨了眨眼。",
		["react"] = 0,
	},
	["work"] = {
		["types"] = {13},
		["none"] = "你开始工作。",
		["target"] = "你和<Target>一起工作。",
		["react"] = 0,
	},
}

