
    MPOWA_MAINFRAME_HEAD = "Modified Power Auras"

    MPOWA_BUTTON_EDIT = "编辑光环"
    MPOWA_BUTTON_ADD = "添加光环"
    MPOWA_BUTTON_REMOVE = "移除光环"
    MPOWA_BUTTON_PROFILE = "配置文件"
    MPOWA_BUTTON_CLOSE = "关闭"
    MPOWA_BUTTON_TEST = "测试"
    MPOWA_BUTTON_TESTALL = "测试全部"
    MPOWA_BUTTON_IMPORT = "导入"
    MPOWA_BUTTON_SAVE = "保存"
    MPOWA_BUTTON_REMOVE = "移除"
    MPOWA_BUTTON_CANCEL = "取消"
    MPOWA_BUTTON_OKAY = "确定"

    MPOWA_CONFIGFRAME_NAME = "配置界面"
    MPOWA_CONFIGFRAME_ANIMATION = "动画"
    MPOWA_CONFIGFRAME_GROUP = "分组"
    MPOWA_CONFIGFRAME_EFFECT_EDITOR = "效果"
    MPOWA_CONFIGFRAME_TIMER_EDITOR = "计时器"
    MPOWA_CONFIGFRAME_SOUND_EDITOR = "声音"
    MPOWA_CONFIGFRAME_ABOUT = "关于"
    MPOWA_PROFILEFRAME_NAME = "配置文件编辑器"
    MPOWA_ICONFRAME_NAME = "图标界面"

    MPOWA_SLIDER_OPACITY = "不透明度:"
    MPOWA_SLIDER_OPACITY_TOOLTIP = "移动此滑块以更改图标的不透明度。"
    MPOWA_SLIDER_POSX = "横向位置:"
    MPOWA_SLIDER_POSX_TOOLTIP = "移动此滑块以更改图标的水平位置。注意：要进一步移动，请释放鼠标并继续拖动或稍微拖回。"
    MPOWA_SLIDER_POSY = "纵向位置:"
    MPOWA_SLIDER_POSY_TOOLTIP = "移动此滑块以更改图标的垂直位置。注意：要进一步移动，请释放鼠标并继续拖动或稍微拖回。"
    MPOWA_SLIDER_SIZE = "大小:"
    MPOWA_SLIDER_SIZE_TOOLTIP = "移动此滑块以更改图标的大小。"
    MPOWA_SLIDER_BEGINSOUND = "开始音效: "
    MPOWA_SLIDER_BEGINSOUND_TOOLTIP = "移动此滑块以更改应用光环时播放的音效文件。"
    MPOWA_SLIDER_ENDSOUND = "结束音效: "
    MPOWA_SLIDER_ENDSOUND_TOOLTIP = "移动此滑块以更改光环消失时播放的音效文件。"

    MPOWA_EDITBOX_TOOLTIP = "在此输入精确的增益名称以触发事件。名称必须正确书写。玩家的光环将自动找到。"
    MPOWA_EDITBOX_NAME = "增益的精确名称:"
    MPOWA_EDITBOX_STACKS_NAME = "层数:"
    MPOWA_EDITBOX_STACKS_TOOLTIP = "在此输入运算符和所需的层数，以激活/取消效果。运算符是必需的，例如：'<5'，'>3'，'=11'，'!5'，'>=0'，'<=6'，'2-8'"
    MPOWA_EDITBOX_DEBUFFDURATION = "持续时间:"
    MPOWA_EDITBOX_DEBUFFDURATION_TOOLTIP = "在此输入敌方减益效果的持续时间。"
    MPOWA_EDITBOX_FLASHANIM = "开始时间:"
    MPOWA_EDITBOX_FLASHANIM_TOOLTIP = "在此输入触发闪烁动画的值。"

    MPOWA_CHECKBUTTON_DEBUFF = "是否为减益效果"
    MPOWA_CHECKBUTTON_DEBUFF_TOOLTIP = "如果光环是减益效果，请勾选此项。"
    MPOWA_CHECKBUTTON_SHOWIFNOTACTIVE = "反转显示"
    MPOWA_CHECKBUTTON_SHOWIFNOTACTIVE_TOOLTIP = "如果光环未激活时图标应可见，请勾选此项。"
    MPOWA_CHECKBUTTON_TIMER = "计时器"
    MPOWA_CHECKBUTTON_TIMER_TOOLTIP = "勾选此项以启用计时器。"
    MPOWA_CHECKBUTTON_SHOWCOOLDOWN = "冷却中显示"
    MPOWA_CHECKBUTTON_SHOWCOOLDOWN_TOOLTIP = "勾选此项以在技能冷却中显示图标。"
    MPOWA_CHECKBUTTON_ENEMYTARGET = "|cFFFF8080敌方目标|r"
    MPOWA_CHECKBUTTON_ENEMYTARGET_TOOLTIP = "勾选此项以使用敌方目标代替你自己。注意：计时器可能不准确。"
    MPOWA_CHECKBUTTON_INCOMBAT = "战斗中"
    MPOWA_CHECKBUTTON_INCOMBAT_TOOLTIP = "选择此项配置图标的显示方式。无 => 忽略战斗状态，勾选 => 战斗中显示，叉号 => 非战斗中显示。"
    MPOWA_CHECKBUTTON_INPARTY = "在队伍中"
    MPOWA_CHECKBUTTON_INPARTY_TOOLTIP = "选择此项配置图标的显示方式。无 => 忽略队伍状态，勾选 => 在队伍中显示，叉号 => 不在队伍中显示。"
    MPOWA_CHECKBUTTON_INRAID = "在团队中"
    MPOWA_CHECKBUTTON_INRAID_TOOLTIP = "选择此项配置图标的显示方式。无 => 忽略团队状态，勾选 => 在团队中显示，叉号 => 不在团队中显示。"
    MPOWA_CHECKBUTTON_ALIVE = "存活"
    MPOWA_CHECKBUTTON_ALIVE_TOOLTIP = "选择此项配置图标的显示方式。无 => 忽略状态，勾选 => 存活时显示，叉号 => 非存活时显示。"
    MPOWA_CHECKBUTTON_MOUNTED = "骑乘状态"
    MPOWA_CHECKBUTTON_MOUNTED_TOOLTIP = "选择此项配置图标的显示方式。无 => 忽略状态，勾选 => 骑乘时显示，叉号 => 非骑乘时显示。"
    MPOWA_CHECKBUTTON_FRIENDLYTARGET = "|cFF66CD00友方目标|r"
    MPOWA_CHECKBUTTON_FRIENDLYTARGET_TOOLTIP = "勾选此项以使用友方目标代替你自己。注意：计时器可能不准确。"
    MPOWA_CHECKBUTTON_ISBATTLEGROUND = "在战场中"
    MPOWA_CHECKBUTTON_ISBATTLEGROUND_TOOLTIP = "选择此项配置图标的显示方式。无 => 忽略状态，勾选 => 在战场中显示，叉号 => 不在战场中显示。"
    MPOWA_CHECKBUTTON_HUNDREDS = "显示百分秒"
    MPOWA_CHECKBUTTON_HUNDREDS_TOOLTIP = "勾选此项以显示百分秒。"
    MPOWA_CHECKBUTTON_COLOR = "自定义颜色："
    MPOWA_CHECKBUTTON_COLOR_TOOLTIP = "勾选此项以在计时器中使用自定义颜色，而不是白色。"
    MPOWA_CHECKBUTTON_BEGINSOUND = "应用光环时播放音效"
    MPOWA_CHECKBUTTON_BEGINSOUND_TOOLTIP = "勾选此项以在应用光环时播放音效。"
    MPOWA_CHECKBUTTON_ENDSOUND = "光环消失时播放音效"
    MPOWA_CHECKBUTTON_ENDSOUND_TOOLTIP = "勾选此项以在光环消失时播放音效。"
    MPOWA_CHECKBUTTON_RAIDMEMBER = "|cFF66CD00团队/团队成员|r"
    MPOWA_CHECKBUTTON_RAIDMEMBER_TOOLTIP = "勾选此项以指定团队成员为目标。"
    MPOWA_CHECKBUTTON_EXACTNAME = "精确名称"
    MPOWA_CHECKBUTTON_EXACTNAME_TOOLTIP = "使用精确名称作为过滤器，而不是模糊过滤器。"
    MPOWA_CHECKBUTTON_FLASHANIM = "闪烁动画"
    MPOWA_CHECKBUTTON_FLASHANIM_TOOLTIP = "勾选此项以启用闪烁动画。"
    MPOWA_CHECKBUTTON_SECS_LEFT = "如果剩余 X 秒"
    MPOWA_CHECKBUTTON_SECS_LEFT_TOOLTIP = "在冷却或增益效果剩余 X 秒时显示。"
    MPOWA_CHECKBUTTON_ININSTANCE = "在团队副本中"
    MPOWA_CHECKBUTTON_ININSTANCE_TOOLTIP = "选择此项配置图标的显示方式。无 => 忽略状态，勾选 => 在团队副本中显示，叉号 => 不在团队副本中显示。"
    MPOWA_EDITBOX_SECONDS = "秒数："
    MPOWA_EDITBOX_SECONDS_TOOLTIP = "在显示光环之前的秒数。"

    MPOWA_SCRIPT_MOUNT_100 = "速度提高100"
    MPOWA_SCRIPT_MOUNT_60 = "速度提高60"

    MPOWA_COLORPICKER_TOOLTIP = "点击此处更改字体颜色。"

    MPOWA_TEXT_ABOUT_MPOWA = "Modified Power Auras是Power Auras插件的高级版本。它更加强大，提供了从大灾变版本中回溯的所有可能功能。此外，它还提供了一些非常有用的自定义功能。"
    MPOWA_TEXT_CREATOR_TITLE = "谁创建了Modified Power Auras？"
    MPOWA_TEXT_CREATOR =
    "Modified Power Auras是由Shino|cFFFF8080-诗诺-|r（Albea）<Synced>在Kronos（Twinstar.cz）上开发的插件。他在Twinstar社区中以Geigerkind的名字出名。"

    MPOWA_TEXT_SPECIALTHANKS_TITLE = "特别感谢："
    MPOWA_TEXT_SPECIALTHANKS = "Sinesther - 最初是他的插件，我只是恰好将其回溯到了经典版本。\nmartinjlowm - 动画组库的创建者"

    MPOWA_TEXT_SUPPORTING_TITLE = "感谢支持！"
    MPOWA_TEXT_SUPPORTING = "目前还没有"

    MPOWA_EDITBOX_PLAYER_NAME = "玩家名字："
    MPOWA_EDITBOX_PLAYER_NAME_TOOLTIP = "输入指定玩家的准确名字。"

    MPOWA_AURA_GONE_SELF = "你身上的(.+)消失了%."
    MPOWA_AURA_GONE_OTHER = "(.+)从(.+)身上消失了%."

    MPOWA_ZONES_MC = "熔火之心"
    MPOWA_ZONES_BWL = "黑翼之巢"
    MPOWA_ZONES_ONY = "奥妮克希亚的巢穴"
    MPOWA_ZONES_ZG = "祖尔格拉布"
    MPOWA_ZONES_AQ401 = "安其拉废墟"
    MPOWA_ZONES_AQ402 = "安其拉神殿"
    MPOWA_ZONES_AQ20 = "安其拉废墟"
    MPOWA_ZONES_NAXX = "纳克萨玛斯"

    MPOWA_CHECKBUTTON_HIDE_STACKS_TOOLTIP = "勾选此项以隐藏堆叠数量"
    MPOWA_CHECKBUTTON_HIDE_STACKS = "隐藏堆叠"
    MPOWA_CHECKBUTTON_USE_DESCRIPTION_TOOLTIP = "勾选此项以同时使用增益图标作为第二个指示器来获取光环信息"
    MPOWA_CHECKBUTTON_USE_DESCRIPTION = "使用图标"
    MPOWA_EDITBOX_SecondSpecifier_TOOLTIP = "插入光环图标的确切名称"
    MPOWA_EDITBOX_SecondSpecifier = "确切图标名称："

    MPOWA_WINDFURY_GAIN = "你获得了风怒图腾。"
    MPOWA_WINDFURY_GAIN2 = "你获得了风怒武器。"
    MPOWA_WINDFURY_GAIN3 = "你获得了风怒效果。"
    MPOWA_WINDFURY_GONE = "风怒图腾从你身上消失。"
    MPOWA_WINDFURY_GONE2 = "风怒武器从你身上消失。"
    MPOWA_WINDFURY_GONE3 = "风怒效果从你身上消失。"

    MPOWA_ONSTART = "开始时"
    MPOWA_ONFINISHED = "结束时"
    
    -- // TODO 多有动画的离开都在报错
    MPOWA_CHECKBUTTON_FADEIN = "淡入"
    MPOWA_CHECKBUTTON_FADEIN_TOOLTIP = "勾选此项，当你的光环出现时会有淡入动画。"
    MPOWA_CHECKBUTTON_FADEOUT = "淡出"
    MPOWA_CHECKBUTTON_FADEOUT_TOOLTIP = "勾选此项，当你的光环消失时会有淡出动画。"
    MPOWA_CHECKBUTTON_GROWIN = "变大"
    MPOWA_CHECKBUTTON_GROWIN_TOOLTIP = "勾选此选项在光环出现时动画变大。"
    MPOWA_CHECKBUTTON_GROWOUT = "变大消失"
    MPOWA_CHECKBUTTON_GROWOUT_TOOLTIP = "勾选此项，当你的光环消失时会有变大消失动画。"
    MPOWA_CHECKBUTTON_ROTATE_TOOLTIP = "勾选此项以在光环出现或消失时使用旋转动画。"
    MPOWA_CHECKBUTTON_ROTATEIN = "旋转进入"
    MPOWA_CHECKBUTTON_ROTATEOUT = "旋转离开"
    MPOWA_CHECKBUTTON_SIZEIN_TOOLTIP = "勾选此项以在光环出现时使用大小变化动画。"
    MPOWA_CHECKBUTTON_SIZEIN = "大小变化"
    MPOWA_CHECKBUTTON_TRANSLATE_TOOLTIP = "勾选此项以在光环消失时使用平移动画。"
    MPOWA_CHECKBUTTON_TRANSLATE = "平移"
    MPOWA_CHECKBUTTON_ESCAPE_TOOLTIP = "勾选此项以在光环出现或消失时使用逸出动画。"
    MPOWA_CHECKBUTTON_ESCAPEIN = "逸出进入"
    MPOWA_CHECKBUTTON_ESCAPEOUT = "逸出离开"
    MPOWA_CHECKBUTTON_BATMAN_TOOLTIP = "勾选此项以在光环出现或消失时使用蝙蝠侠动画。"
    MPOWA_CHECKBUTTON_BATMANIN = "蝙蝠侠进入"
    MPOWA_CHECKBUTTON_BATMANOUT = "蝙蝠侠离开"
    MPOWA_CHECKBUTTON_SHRINK_TOOLTIP = "勾选此项以在光环消失时使用缩小动画。"
    MPOWA_CHECKBUTTON_SHRINK = "缩小"

    MPOWA_SLIDER_ANIMDURATION_TOOLTIP = "移动此滑块以改变光环动画的持续时间。"
    MPOWA_SLIDER_ANIMDURATION = "动画持续时间"
    MPOWA_SLIDER_TRANSLATE_TOOLTIP = "移动此滑块以改变平移动画的偏移量。"
    MPOWA_SLIDER_TRANSLATEX = "X轴平移"
    MPOWA_SLIDER_TRANSLATEY = "Y轴平移"
    MPOWA_SLIDER_FADEALPHA_TOOLTIP = "移动此滑块以改变光环的透明度变化值。"
    MPOWA_SLIDER_FADEALPHA = "渐变透明度"
    MPOWA_SLIDER_SCALEFACTOR_TOOLTIP = "移动此滑块以改变动画的缩放因子。"
    MPOWA_SLIDER_SCALEFACTOR = "缩放因子"

    MPOWA_CHECKBUTTON_ISDYNAMICGROUP_TOOLTIP = "勾选此项将将此光环设置为动态组。您可以通过在适当的字段中输入光环编号来将其他光环添加到该组中。"
    MPOWA_CHECKBUTTON_ISDYNAMICGROUP = "动态组"
    MPOWA_EDITBOX_GROUPNUMBER_TOOLTIP = "输入动态组父光环的编号。"
    MPOWA_EDITBOX_GROUPNUMBER = "输入组编号"
    MPOWA_EDITBOX_FUNCTION_TOOLTIP = "输入自定义函数。返回true以显示光环，返回false以隐藏光环。"

    MPOWA_EDITBOX_TOOLTIP_ICONPATH = "图标路径。如果列表中没有或者自动查找不到，请在此处输入路径。"

    MPOWA_CHECKBUTTON_SORTED = "按时间排序"
    MPOWA_CHECKBUTTON_SORTED_TOOLTIP = "按时间升序对组中的光环进行排序。"

    MPOWA_SLIDER_DYNAMICORIENTATION = "方向："
    MPOWA_SLIDER_DYNAMICORIENTATION_TOOLTIP = "选择组增长的方向。"

    MPOWA_CHECKBUTTON_DYCNTER = "不居中"
    MPOWA_CHECKBUTTON_DYCNTER_TOOLTIP = "不自动更改组的偏移量以居中。"

    MPOWA_SLIDER_FONT = "字体："
    MPOWA_SLIDER_FONT_TOOLTIP = "滑动以更改计时器的字体。"

    MPOWA_SLIDER_SPACING = "间距："
    MPOWA_SLIDER_SPACING_TOOLTIP = "滑动以更改光环之间的间距。"

    MPOWA_SLIDER_BLENDMODE = "渲染："
    MPOWA_SLIDER_BLENDMODE_TOOLTIP = "滑动以更改光环的混合模式。"

    MPOWA_CHECKBUTTON_MINUTES = "显示时间 >60秒"
    MPOWA_CHECKBUTTON_MINUTES_TOOLTIP = "当剩余时间大于60秒时显示分钟。"

    MPOWA_SLIDER_FONTSIZE_TOOLTIP = "滑动以更改计时器堆叠字体的大小。"
    MPOWA_SLIDER_FONTSIZE = "堆叠字体大小："

