if (GetLocale() == "frFR") then 

PowaAnim = {};
PowaAnim[0] = "[Invisible]";
PowaAnim[1] = "Statique";
PowaAnim[2] = "Clignotement";
PowaAnim[3] = "Agrandir";
PowaAnim[4] = "Pulsation";
PowaAnim[5] = "Effet bulle";
PowaAnim[6] = "Goutte d'eau";
PowaAnim[7] = "Electrique";
PowaAnim[8] = "R\195\169tr\195\169cir";
PowaAnim[9] = "Flamme";
PowaAnim[10] = "Orbite";

PowaDisplay = {};
PowaDisplay[0] = "[Aucun]";
PowaDisplay[1] = "Zoom Avant";
PowaDisplay[2] = "Zoom Arriere";
PowaDisplay[3] = "Transparence seule";
PowaDisplay[4] = "Gauche";
PowaDisplay[5] = "Haut-Gauche";
PowaDisplay[6] = "Haut";
PowaDisplay[7] = "Haut-Droite";
PowaDisplay[8] = "Droite";
PowaDisplay[9] = "Bas-Droite";
PowaDisplay[10] = "Bas";
PowaDisplay[11] = "Bas-Gauche";

PowaText = {
	welcome = "Tapez /powa pour afficher les options.",

	aucune = "Aucune",
	aucun = "Aucun",
	largeur = "Largeur",
	hauteur = "Hauteur",

	aideTexture = "La texture \195\160 afficher. Vous pouvez facilement remplacer les textures en changeant les fichier Aura#.tga du dossier de l'AddOn.",
	aideAnim1 = "Anime la texture ou pas, avec diff\195\169rents effets.",
	aideAnim2 = "Cette animation sera affich\195\169e avec moins d'opacit\195\169 que la principale. Attention, afin de ne pas surcharger le tout, une seule animation secondaire sera affich\195\169e a la fois.",
	aideDeform = "Etire la texture vers le haut ou en largeur.",
	aideColor = "Cliquez ici pour changer la couleur de la texture.",
	aideBuff = "Entrez ici le nom du buff, ou une partie du nom, qui doit activer/d\195\169sactiver l'effet. Vous pouvez entrer plusieurs noms s'ils sont s\195\169par\195\169 comme il convient (ex: Super Buff/Puissance)",
	aideBuff2 = "Entrez ici le nom du d\195\169buff, ou une partie du nom, qui doit activer/d\195\169sactiver l'effet. Vous pouvez entrer plusieurs noms s'ils sont s\195\169par\195\169 comme il convient (ex: Maladie noire/Peste)",
	aideBuff3 = "Entrez ici le type du d\195\169buff qui doit activer ou d\195\169sactiver l'effet (Poison, Maladie, Mal\195\169diction, Magie ou Aucun). Vous pouvez aussi entrer plusieurs types de d\195\169buffs \195\160 la fois.",
	aideDebuff = "Cochez cette case si vous voulez que cet effet s'applique plut\195\180t \195\160 un d\195\169buff.",
	aideDebuffType = "Cochez cette case si vous voulez que cet effet s'applique \195\160  un type de d\195\169buff particulier (commun\195\169ment : Poison, Maladie, Mal\195\169diction, Magie...)",
	aideShowTimer = "Cochez cette case pour afficher la dur\195\169e de cet effet.",
	aideInverse = "Cochez cette case pour afficher cet effet uniquement quand le buff/d\195\169buff n'est pas actif.",
	aideIgnoreMaj = "Cochez cette case pour ignorer les majuscules/minuscules du nom des buffs/d\195\169buffs.",
	aideDisable = "D\195\169sactive tous les effets",
	aideDuration = "Pass\195\169 ce d\195\169lai, l'animation sera masqu\195\169e (0 pour d\195\169sactiver)",
	aideListe = "Ceci est la liste des effets disponibles par tous les personnages. Attention, seuls les effets pr\195\169sents dans l'\195\169diteur d'effet seront actifs.",
	aideMaxTex = "Defini le maximum de textures disponibles dans l'Editeur d'Effets. Si vous rajoutez des textures en les mettant dans le dossier de l'AddOn (nomm\195\169es de AURA1.tga \195\160 AURA50.tga) c'est ici qu'il faudra le signaler.",
	aideClear = "Supprime tous les effets qui n'ont pas de nom, et trie les effets restants par type.",
	aideAddEffect = "Ajoute une page d'effet.",
	nomBuff = "Nom du Buff",
	nomDebuff = "Nom du Debuff",
	nomDebuffType = "Type de Debuff",
	nomCheckBuff = "Buff",
	nomCheckDebuff = "Debuff",
	nomCheckDebuffType = "Type du Debuff",
	nomCheckShowTimer = "Afficher la dur\195\169e",
	nomCheckInverse = "Afficher si inactif",
	nomCheckIgnoreMaj = "Ignorer les majuscules",
	nomTexture = "Texture",
	nomAnim1 = "Animation principale",
	nomAnim2 = "Animation secondaire",
	nomSpeed = "Vitesse d'Anim.",
	nomBegin = "Animation de d\195\169part",
	nomEnd = "Animation de fin",
	nomDuration = "Dur\195\169e de l'Anim.",
	nomSymetrie = "Sym\195\169trie",
	nomAlpha = "Transparence",
	nomPos = "Position",
	nomTaille = "Taille",
	nomDeform = "D\195\169formation",
	nomTest = "Tester",
	nomHide = "Tout masquer",
	nomClose = "Fermer",
	nomTitre = "Effet",
	nomListe = "Liste >>",
	nomCentiemes = "Afficher centiemes",
	nomDual = "Afficher 2 dur\195\169es",
	nomDisable = "D\195\169sactiver Power Auras",
	nomEffectEditor = "Editeur d'Effets",
	nomAdvOptions = "Options Avanc\195\169es",
	nomMaxTex = "Maximum de textures disponibles",
	nomTabAnim = "Animation",
	nomTabActiv = "Activation",
	listheader = "Liste des Buffs/Debuffs",
	listdelete = "Efface cet effet.",
	listload = "Copie cet effet dans la fenetre d'\195\169dition en cours.",
	listadd = ">> Ajouter",
	listaideadd = "Sauvegarde dans la liste l'effet actuellement \195\169dit\195\169.",
	erreur1 = "Erreur : L'effet actuel n'a aucun nom.",
	erreur2 = "Erreur : Un effet portant ce nom existe d\195\169j\195\160.",
	erreur3 = "Erreur : Pas assez de place pour sauver."
};

else

PowaAnim = {};
PowaAnim[0] = "[Invisible]";
PowaAnim[1] = "Static";
PowaAnim[2] = "Flashing";
PowaAnim[3] = "Growing";
PowaAnim[4] = "Pulse";
PowaAnim[5] = "Bubble";
PowaAnim[6] = "Water drop";
PowaAnim[7] = "Electric";
PowaAnim[8] = "Shrinking";
PowaAnim[9] = "Flame";
PowaAnim[10] = "Orbit";

PowaDisplay = {};
PowaDisplay[0] = "[None]";
PowaDisplay[1] = "Zoom In";
PowaDisplay[2] = "Zoom Out";
PowaDisplay[3] = "Opacity only";
PowaDisplay[4] = "Left";
PowaDisplay[5] = "Top-Left";
PowaDisplay[6] = "Top";
PowaDisplay[7] = "Top-Right";
PowaDisplay[8] = "Right";
PowaDisplay[9] = "Bottom-Right";
PowaDisplay[10] = "Bottom";
PowaDisplay[11] = "Bottom-Left";

PowaText = {
	welcome = "键入/ powa以查看选项。",

	aucune = "无",
	aucun = "无",
	largeur = "宽度",
	hauteur = "高度",

	aideTexture = "要显示的纹理材质。您可以通过更改Addon目录中的Aura＃.tga文件轻松替换纹理。",
	aideAnim1 = "动画纹理材质有或没有，与各种效果。",
	aideAnim2 = "与主动画相比，此动画的显示颜色较少。 注意，为了不超载屏幕，只能同时显示一个辅助动画。",
	aideDeform = "在高度或宽度上拉伸纹理。",
	aideColor = "点击此处更改纹理材质的颜色。",
	aideBuff = "在这里输入buff的名称，或名称的一部分，必须激活/禁用效果。 您可以输入几个名称，如果它们是分开的（例如：超级魔法力/力量）",
	aideBuff2 = "在此输入debuff的名称，或名称的一部分，必须激活/禁用效果。 你可以输入几个名字，如果它们是分开的（例如：黑暗病/瘟疫）",
	aideBuff3 = "在这里输入必须激活或停用效果（毒药，疾病，诅咒，魔法或无）的debuff类型。 您还可以输入多种类型的debuff。",
	aideDebuff = "检查这个是否适用于debuff。",
	aideDebuffType = "勾选，使此效果适用于特定类型的debuff（毒药，疾病，诅咒，魔法...）",
	aideShowTimer = "勾选来显示这个效果的定时器。",
	aideInverse = "勾选，只有当buff / debuff不活动时显示此效果。",	
	aideIgnoreMaj = "勾选，忽略buff / debuff名称的大小写。",
	aideDisable = "禁用所有效果",
	aideDuration = "此后，此效果将消失（0停用）活动。",
	aideListe = "这是所有字符可用的效果列表。 当心，只有效果编辑器中的效果才会激活。",
	aideMaxTex = "定义效果编辑器上可用的最大纹理材质数。 如果在Mod目录中添加纹理（名称为AURA1.tga到AURA50.tga），则必须在此处指明正确的数字。",
	aideClear = "删除所有没有任何名称的效果，并按类型排序其他。",
	aideAddEffect = "添加一些效果。",
	nomBuff = "Buff的名称",
	nomDebuff = "Debuff的名称",
	nomDebuffType = "Debuff的类型",
	nomCheckBuff = "Buff",
	nomCheckDebuff = "Debuff",
	nomCheckDebuffType = "Debuff类型",
	nomCheckShowTimer = "显示计时器",
	nomCheckInverse = "不活动时显示",
	nomCheckIgnoreMaj = "忽略大写字母",	
	nomTexture = "纹理材质",
	nomAnim1 = "主要动画",
	nomAnim2 = "辅助动画",
	nomSpeed = "动画速度",
	nomBegin = "开始动画",
	nomEnd = "结束动画",
	nomDuration = "动画持续时间",
	nomSymetrie = "对称",
	nomAlpha = "不透明度",
	nomPos = "位置",
	nomTaille = "尺寸",
	nomDeform = "变形",
	nomTest = "测试",
	nomHide = "全部藏起来",
	nomClose = "关闭",
	nomTitre = "效果",
	nomListe = "列表 >>",
	nomCentiemes = "显示百分之",
	nomDual = "显示2个计时器",
	nomDisable = "停用Power Auras",
	nomEffectEditor = "效果编辑器",
	nomAdvOptions = "高级选项",
	nomMaxTex = "最大可用的纹理",
	nomTabAnim = "动画",
	nomTabActiv = "激活",
	listheader = "Buffs/Debuffs 列表",
	listdelete = "删除此效果。",
	listload = "将此效果复制到当前版本窗口。",
	listadd = ">> 添加",
	listaideadd = "在列表中保存当前编辑的效果。",
	erreur1 = "错误：当前效果没有任何名称。",
	erreur2 = "错误：保存的效果已经有这个名字。",
	erreur3 = "错误：没有足够的空间来保存这个效果。"
};

end

