
	TITAN_DEBUG = "<Titan>";
	TITAN_INFO = "<Titan>"
	
	TITAN_NA = "N/A";
	TITAN_SECONDS = "秒";
	TITAN_MINUTES = "分";
	TITAN_HOURS = "小时";
	TITAN_DAYS = "天";
	TITAN_SECONDS_ABBR = "秒";
	TITAN_MINUTES_ABBR = "分";
	TITAN_HOURS_ABBR = "小时";
	TITAN_DAYS_ABBR = "天";
	TITAN_MILLISECOND = "毫秒";
	TITAN_KILOBYTES_PER_SECOND = "KB/s";
	TITAN_KILOBITS_PER_SECOND = "kbps"
	TITAN_MEGABYTE = "MB";
	
	TITAN_MOVABLE_TOOLTIP = "按住鼠标来拖动";

	TITAN_PANEL_ERROR_DUP_PLUGIN = " 似乎注册了两次，这会导致泰坦面板功能错误，请修正这个问题"
	
	TITAN_PANEL = "Titan 面板";
	TITAN_PANEL_MENU_TITLE = "Titan 面板设置";
	TITAN_PANEL_MENU_HIDE = "隐藏";
	TITAN_PANEL_MENU_CUSTOMIZE = "自定义";
	TITAN_PANEL_MENU_SHOW_COLORED_TEXT = "使用彩色文字";
	TITAN_PANEL_MENU_SHOW_ICON = "显示图标";
	TITAN_PANEL_MENU_SHOW_LABEL_TEXT = "显示标签文字";
	TITAN_PANEL_MENU_AUTOHIDE = "自动隐藏";
	TITAN_PANEL_MENU_BGMINIMAP = "战场小地图";
	TITAN_PANEL_MENU_CENTER_TEXT = "文字居中";
	TITAN_PANEL_MENU_DISPLAY_ONTOP = "信息面板置顶";
	TITAN_PANEL_MENU_DISPLAY_BOTH = "开启屏幕下方面板";
	TITAN_PANEL_MENU_DISABLE_PUSH = "禁止屏幕调节";
	TITAN_PANEL_MENU_BUILTINS = "Titan 内置插件";
	TITAN_PANEL_MENU_LEFT_SIDE = "左侧";
	TITAN_PANEL_MENU_RIGHT_SIDE = "右侧";
	TITAN_PANEL_MENU_LOAD_SETTINGS = "加载设置";
	TITAN_PANEL_MENU_DOUBLE_BAR = "第二信息条";
	TITAN_PANEL_MENU_OPTIONS = "设置";
	TITAN_PANEL_MENU_PLUGINS = "插件";
	TITAN_PANEL_MENU_VERSION_SHOWN = "显示插件版本";
	TITAN_PANEL_MENU_DISBALE_FONT = "禁用字体比例";
	TITAN_PANEL_MENU_CATEGORIES = {"其他增强插件"};
	TITAN_PANEL_MENU_TOOLTIPS_SHOWN = "显示提示信息";
	
	TITAN_AUTOHIDE_TOOLTIP = "面板自动隐藏开关";
	TITAN_AUTOHIDE_MENU_TEXT = "自动隐藏";
	
	TITAN_AMMO_FORMAT = "%d";
	TITAN_AMMO_BUTTON_LABEL_AMMO = "弹药: ";
	TITAN_AMMO_BUTTON_LABEL_THROWN = "投掷:";
	TITAN_AMMO_BUTTON_LABEL_AMMO_THROWN = "弹药/投掷:";
	TITAN_AMMO_TOOLTIP = "已装备的弹药/投掷武器数量";
	TITAN_AMMO_MENU_TEXT = "弹药";
	TITAN_AMMO_THROWN_KEYWORD = "飞";
	
	TITAN_BAG_FORMAT = "%d/%d";
	TITAN_BAG_BUTTON_LABEL = "背包: ";
	TITAN_BAG_TOOLTIP = "背包状态";
	TITAN_BAG_TOOLTIP_HINTS = "左键单击打开所有包裹.";
	TITAN_BAG_MENU_TEXT = "背包";
	TITAN_BAG_MENU_SHOW_USED_SLOTS = "显示已用空间";
	TITAN_BAG_MENU_SHOW_AVAILABLE_SLOTS = "显示剩余空间";
	TITAN_BAG_MENU_IGNORE_AMMO_POUCH_SLOTS = "忽略弹药包/箭袋";
	TITAN_BAG_AMMO_POUCH_NAMES = {"弹药", "箭袋", "子弹袋", "子弹", "飞刀"};

	TITAN_BGMINIMAP_MENU_TEXT = "战场小地图"
	TITAN_BGMINIMAP_TOOLTIP = "锁定战场小地图"
	
	TITAN_CLOCK_TOOLTIP = "时钟";
	TITAN_CLOCK_TOOLTIP_VALUE = "当前时差: ";
	TITAN_CLOCK_TOOLTIP_HINT1 = "左键单击调整时差"
	TITAN_CLOCK_TOOLTIP_HINT2 = "和12/24小时制显示.";
	TITAN_CLOCK_CONTROL_TOOLTIP = "时差:";
	TITAN_CLOCK_CONTROL_TITLE = "时差";
	TITAN_CLOCK_CONTROL_HIGH = "+12";
	TITAN_CLOCK_CONTROL_LOW = "-12";
	TITAN_CLOCK_CHECKBUTTON = "24小时制";
	TITAN_CLOCK_CHECKBUTTON_TOOLTIP = "切换12/24小时制显示";
	TITAN_CLOCK_MENU_TEXT = "时钟";
	TITAN_CLOCK_MENU_DISPLAY_ON_RIGHT_SIDE = "显示在最右侧";
	
	TITAN_COORDS_FORMAT = "(%.d, %.d)";
	TITAN_COORDS_BUTTON_LABEL = "区域:";
	TITAN_COORDS_TOOLTIP = "区域信息";
	TITAN_COORDS_TOOLTIP_HINTS_1 = "Shift + 左键单击将当前位置";
	TITAN_COORDS_TOOLTIP_HINTS_2 = "信息加入到聊天输入窗口.";
	TITAN_COORDS_TOOLTIP_ZONE = "区域: ";
	TITAN_COORDS_TOOLTIP_SUBZONE = "具体地点: ";
	TITAN_COORDS_TOOLTIP_PVPINFO = "PVP 信息: ";
	TITAN_COORDS_TOOLTIP_HOMELOCATION = "炉石地点";
	TITAN_COORDS_TOOLTIP_INN = "旅馆: ";
	TITAN_COORDS_MENU_TEXT = "区域";
	TITAN_COORDS_MENU_SHOW_ZONE_ON_PANEL_TEXT = "显示区域文字";
	TITAN_COORDS_MENU_SHOW_COORDS_ON_MAP_TEXT = "在世界地图上显示坐标";
	TITAN_COORDS_MAP_COORDS_TEXT = "%d, %d";
	TITAN_COORDS_MAP_CURSOR_COORDS_TEXT = "指针坐标(X,Y): %s";
	TITAN_COORDS_MAP_PLAYER_COORDS_TEXT = "玩家坐标(X,Y): %s";
	
	TITAN_FPS_FORMAT = "%.1f";
	TITAN_FPS_BUTTON_LABEL = "FPS: ";
	TITAN_FPS_MENU_TEXT = "FPS";
	TITAN_FPS_TOOLTIP_CURRENT_FPS = "当前 FPS: ";
	TITAN_FPS_TOOLTIP_AVG_FPS = "平均 FPS: ";
	TITAN_FPS_TOOLTIP_MIN_FPS = "最低 FPS: ";
	TITAN_FPS_TOOLTIP_MAX_FPS = "最高 FPS: ";
	TITAN_FPS_TOOLTIP = "每秒帧数";
	
	TITAN_HONOR_BUTTON_LABEL_RANK = RANK..":";
	TITAN_HONOR_BUTTON_LABEL_HK = "荣誉击杀: ";
	TITAN_HONOR_BUTTON_LABEL_DK = "非荣誉击杀: ";
	TITAN_HONOR_TOOLTIP = "PVP荣誉信息";
	TITAN_HONOR_MENU_TEXT = "PVP荣誉";
	
	TITAN_LATENCY_FORMAT = "%d"..TITAN_MILLISECOND;
	TITAN_LATENCY_BANDWIDTH_FORMAT = "%.3f "..TITAN_KILOBYTES_PER_SECOND;
	TITAN_LATENCY_BUTTON_LABEL = "延迟: ";
	TITAN_LATENCY_TOOLTIP = "网络状态";
	TITAN_LATENCY_TOOLTIP_LATENCY = "延迟: ";
	TITAN_LATENCY_TOOLTIP_BANDWIDTH_IN = "接收带宽: ";
	TITAN_LATENCY_TOOLTIP_BANDWIDTH_OUT = "发送带宽: ";
	TITAN_LATENCY_MENU_TEXT = "网络延迟";
	
	TITAN_LOOTTYPE_BUTTON_LABEL = "分配: ";
	TITAN_LOOTTYPE_FREE_FOR_ALL = "自由拾取";
	TITAN_LOOTTYPE_ROUND_ROBIN = "轮流拾取";
	TITAN_LOOTTYPE_MASTER_LOOTER = "队长分配";
	TITAN_LOOTTYPE_GROUP_LOOT = "队伍分配";
	TITAN_LOOTTYPE_NEED_BEFORE_GREED = "需求优先";
	TITAN_LOOTTYPE_TOOLTIP = "分配方式";
	TITAN_LOOTTYPE_MENU_TEXT = "分配";
	
	TITAN_MEMORY_FORMAT = "%.3f"..TITAN_MEGABYTE;
	TITAN_MEMORY_RATE_FORMAT = "%.3f"..TITAN_KILOBYTES_PER_SECOND;
	TITAN_MEMORY_BUTTON_LABEL = "内存: ";
	TITAN_MEMORY_TOOLTIP = "插件内存占用";
	TITAN_MEMORY_TOOLTIP_CURRENT_MEMORY = "当前: ";
	TITAN_MEMORY_TOOLTIP_INITIAL_MEMORY = "初始: ";
	TITAN_MEMORY_TOOLTIP_INCREASING_RATE = "增长率: ";
	TITAN_MEMORY_TOOLTIP_GC_INFO = "内存释放信息: ";
	TITAN_MEMORY_TOOLTIP_GC_THRESHOLD = "内存释放界限: ";
	TITAN_MEMORY_TOOLTIP_TIME_TO_GC = "下次释放时间: "
	TITAN_MEMORY_MENU_TEXT = "内存";
	TITAN_MEMORY_MENU_RESET_SESSION = "重置内存数据";
	
	TITAN_MONEY_GOLD = "金";
	TITAN_MONEY_SILVER = "银";
	TITAN_MONEY_COPPER = "铜";
	TITAN_MONEY_FORMAT = "%d"..TITAN_MONEY_GOLD..", %d"..TITAN_MONEY_SILVER..", %d"..TITAN_MONEY_COPPER;
	TITAN_MONEY_MENU_TEXT = "金钱";
	TITAN_MONEY_MENU_RESET_SESSION = "重置金钱统计";
	TITAN_MONEY_TOOLTIP = "显示金钱变化";
	TITAN_MONEY_TOOLTIP_HINTS = "左键单击拿取金钱.";
	TITAN_MONEY_TOOLTIP_CURRENT = "当前: ";
	TITAN_MONEY_TOOLTIP_INITIAL = "初始: ";
	TITAN_MONEY_TOOLTIP_EARNED = "收入: ";
	TITAN_MONEY_TOOLTIP_LOST = "支出: ";
	TITAN_MONEY_TOOLTIP_EARNED_HOUR = "每小时获取: ";
	TITAN_MONEY_TOOLTIP_LOST_HOUR = "每小时花费: ";
	
	TITAN_PERFORMANCE_TOOLTIP = "机器性能";
	TITAN_PERFORMANCE_MENU_TEXT = "FPS/延迟/内存";
	TITAN_PERFORMANCE_MENU_SHOW_FPS = "显示FPS";
	TITAN_PERFORMANCE_MENU_SHOW_LATENCY = "显示网络延迟";
	TITAN_PERFORMANCE_MENU_SHOW_MEMORY = "显示插件内存使用";

  TITAN_TRANS_TOOLTIP = "透明度控制";
	TITAN_TRANS_TOOLTIP_VALUE = "当前面板透明度: ";
	TITAN_TRANS_TOOLTIP_HINT1 = "左键点击调整";
	TITAN_TRANS_TOOLTIP_HINT2 = "面板透明度.";
	TITAN_TRANS_CONTROL_TOOLTIP = "面板透明度:";
	TITAN_TRANS_CONTROL_TITLE = "透明度";
	TITAN_TRANS_CONTROL_HIGH = "100%";
	TITAN_TRANS_CONTROL_LOW = "0%";
	TITAN_TRANS_MENU_TEXT = "透明度";
	
	TITAN_UISCALE_TOOLTIP = "UI/面板缩放";
	TITAN_UISCALE_TOOLTIP_VALUE_UI = "UI比例: ";
	TITAN_UISCALE_TOOLTIP_VALUE_PANEL = "面板比例: ";
	TITAN_UISCALE_TOOLTIP_VALUE_FONT = "字体比例: ";
	TITAN_UISCALE_TOOLTIP_HINT1 = "左键点击调整面板或";
	TITAN_UISCALE_TOOLTIP_HINT2 = "游戏界面(UI)的尺寸大小.";
	TITAN_UISCALE_CONTROL_TOOLTIP_UI = "UI比例: ";
	TITAN_UISCALE_CONTROL_TOOLTIP_PANEL = "面板比例: ";
	TITAN_UISCALE_CONTROL_TOOLTIP_FONT = "字体比例: ";
	TITAN_UISCALE_CONTROL_TITLE_UI = "UI比例";
	TITAN_UISCALE_CONTROL_TITLE_PANEL = "面板比例";
	TITAN_UISCALE_CONTROL_TITLE_FONT = "字体比例";
	TITAN_UISCALE_CONTROL_HIGH_UI = "100%";
	TITAN_UISCALE_CONTROL_HIGH_PANEL = "125%";
	TITAN_UISCALE_CONTROL_HIGH_FONT = "200%";
	TITAN_UISCALE_CONTROL_LOW_UI = "64%";
	TITAN_UISCALE_CONTROL_LOW_PANEL = "75%";
	TITAN_UISCALE_CONTROL_LOW_FONT = "50%";
	TITAN_UISCALE_MENU_TEXT = "UI/面板缩放";
	
	TITAN_VOLUME_TOOLTIP = "音量控制";
	TITAN_VOLUME_TOOLTIP_VALUE = "主音量: ";
	TITAN_VOLUME_TOOLTIP_HINT1 = "左键点击调整"
	TITAN_VOLUME_TOOLTIP_HINT2 = "主音量数值.";
	TITAN_VOLUME_CONTROL_TOOLTIP = "主音量: ";
	TITAN_VOLUME_CONTROL_TITLE = "音量";
	TITAN_VOLUME_CONTROL_HIGH = "高";
	TITAN_VOLUME_CONTROL_LOW = "低";
	TITAN_VOLUME_MENU_TEXT = "音量";
	
	TITAN_XP_FORMAT = "%d";
	TITAN_XP_PERCENT_FORMAT = TITAN_XP_FORMAT.." (%.1f%%)";
	TITAN_XP_BUTTON_LABEL_XPHR_LEVEL = "经验/小时(当前等级): ";
	TITAN_XP_BUTTON_LABEL_XPHR_SESSION = "经验/小时(本次连接): ";
	TITAN_XP_BUTTON_LABEL_TOLEVEL_TIME_LEVEL = "升级时间: ";
	TITAN_XP_BUTTON_LABEL_TOLEVEL_TIME_SESSION = "升级时间: ";
	TITAN_XP_TOOLTIP = "经验信息";
	TITAN_XP_TOOLTIP_TOTAL_TIME = "总共游戏时间: ";
	TITAN_XP_TOOLTIP_LEVEL_TIME = "当前等级游戏时间: ";
	TITAN_XP_TOOLTIP_SESSION_TIME = "本次连接时间: ";
	TITAN_XP_TOOLTIP_TOTAL_XP = "当前升级所需经验: ";
	TITAN_XP_TOOLTIP_LEVEL_XP = "当前等级获得经验: ";
	TITAN_XP_TOOLTIP_TOLEVEL_XP = "升级还需经验: ";
	TITAN_XP_TOOLTIP_SESSION_XP = "本次连接获得经验: ";
	TITAN_XP_TOOLTIP_XPHR_LEVEL = "经验/小时(当前等级):";
	TITAN_XP_TOOLTIP_XPHR_SESSION = "经验/小时(本次连接):";
	TITAN_XP_TOOLTIP_TOLEVEL_LEVEL = "升级时间(按等级效率):";
	TITAN_XP_TOOLTIP_TOLEVEL_SESSION = "升级时间(按连接效率):";
	TITAN_XP_MENU_TEXT = "经验";
	TITAN_XP_MENU_SHOW_XPHR_THIS_LEVEL = "显示当前等级每小时经验";
	TITAN_XP_MENU_SHOW_XPHR_THIS_SESSION = "显示本次连接每小时经验";
	TITAN_XP_MENU_RESET_SESSION = "重置经验统计";
	
	TITAN_REGEN_MENU_TEXT 		= "恢复"
	TITAN_REGEN_MENU_TOOLTIP_TITLE	= "恢复速度"
	TITAN_REGEN_MENU_SHOW1 		= "显示"
	TITAN_REGEN_MENU_SHOW2 		= "生命"
	TITAN_REGEN_MENU_SHOW3 		= "法力"
	TITAN_REGEN_MENU_SHOW4		= "百分比"
	TITAN_REGEN_BUTTON_TEXT_HP 		= "生命: "..HIGHLIGHT_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE;
	TITAN_REGEN_BUTTON_TEXT_HP_PERCENT 	= "生命: "..HIGHLIGHT_FONT_COLOR_CODE.."%.2f"..FONT_COLOR_CODE_CLOSE;
	TITAN_REGEN_BUTTON_TEXT_MP 		= "法力: "..HIGHLIGHT_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE;
	TITAN_REGEN_BUTTON_TEXT_MP_PERCENT 	= "法力: "..HIGHLIGHT_FONT_COLOR_CODE.."%.2f"..FONT_COLOR_CODE_CLOSE;
	TITAN_REGEN_TOOLTIP1 		= "生命: \t"..GREEN_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE.." / " ..HIGHLIGHT_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE.." ("..RED_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE..")";
	TITAN_REGEN_TOOLTIP2 		= "法力: \t"..GREEN_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE.." / " ..HIGHLIGHT_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE.." ("..RED_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE..")";
	TITAN_REGEN_TOOLTIP3 		= "最高生命恢复值: \t"..HIGHLIGHT_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE;
	TITAN_REGEN_TOOLTIP4 		= "最低生命恢复值: \t"..HIGHLIGHT_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE;
	TITAN_REGEN_TOOLTIP5 		= "最高法力恢复值: \t"..HIGHLIGHT_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE;
	TITAN_REGEN_TOOLTIP6 		= "最差法力恢复值: \t"..HIGHLIGHT_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE;
	TITAN_REGEN_TOOLTIP7		= "上次战斗法力恢复值: \t"..HIGHLIGHT_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE.." ("..GREEN_FONT_COLOR_CODE.."%.2f"..FONT_COLOR_CODE_CLOSE.."%%)";


	TITAN_PLUGINS_MENU_TITLE = "插件菜单";
	
	CUSTOMIZATION_FEATURE_COMING_SOON = "功能开发中...";

