-- When translating, please leave all tokens ([item], etc) in english, the parser will not handle translated tokens. Thanks =)
local L = AceLibrary("AceLocale-2.2"):new("XLootMaster")

L:RegisterTranslations("zhCN", function()
	return {
		["Self loot"] = "个人拾取",
		["Priority Looters"] = "团队拾取",
		["No priority players"] = "无特殊拾取优先级",
		["Possible victims"] = "团队标记",
		["Move up"] = "上移",
		["Move Down"] = "下移",
		["Remove"] = "移除",
		["Random"] = "随机",
		["Rolls"] = "Roll点",
		["Give to random player"] = "分配给随机玩家",
		["Clear list and announce new roll"] = "清空列表并宣布新的Roll点",
		["|cFF2255FFListening... |cFF44FF44%s|cFF2255FF seconds left"] = "|cFF2255FF提示： |cFF44FF44剩余：%s|cFF2255FF 秒",
		["|CFFBBBBBBRoll finished"] = "|CFFBBBBBBRoll点 结束",
		[">> Priority configuration"] = ">> 优先级配置",
		["Never"] = "从不",
		["XLoot Master"] = "XLoot Master",
		["XLoot Master plugin, replacement for the standard Master Looter dropdown."] = "XLoot Master插件，替代标准Master Looter下拉列表。",
		["Item tooltip"] = "物品提示",
		["Show a tooltip for the ML item when mousing over it."] = "当鼠标悬停在物品上时显示主分配物品的提示信息。",
		["Player tooltip"] = "玩家提示",
		["Show a tooltip for each player when mousing over them."] = "鼠标悬停在每个玩家身上时，显示他们的提示。",
		["Value utilities"] = true,
		["Various tools such as tracking dkp assignments, broadcasting value along with assignment, and such. |cffff0000Doesn't do much yet.|r"] = true,
		["Awarded item text"] = true,
		["Default: |cffff0000[name] awarded [item][method]|r\n[name] is replaced with the name of the player, \n[item] with the item link, \n[method] with any special note (dkp, random), if it exists, eg: ' (Random)'."] = true,
		["A string containing any of [range], [item], or [time]"] = true,
		["Thresholds"] = true,
		["Confirmation threshold"] = true,
		["The lowest quality of item to open the assignment confirmation window for."] = true,
		["Item value threshold"] = true,
		["The lowest quality of item to open the assignment |cFF22EE22and value|r confirmation window for."] = true,
		["Announce to group..."] = true,
		["Announce to /rw..."] = true,
		["Announce to guild..."] = true,
		["Randomization"] = true,
		["Random menu"] = true,
		["Show the Random menu for loot distribution."] = true,
		["Capture /rolls"] = true,
		["Capture party member /roll #'s"] = true,
		["Show all rolls"] = true,
		["If enabled, show all rolls during a request, even ones not matching set range."] = true,
		["Roll timeout"] = true,
		["Length of time to capture rolls"] = true,
		["Roll range"] = true,
		["Range to request players to roll in"] = true,
		["Roll request text"] = true,
		["Default: |cffff0000Attention! Please /roll [range] for [item]. Ends in [time] seconds.|r\n[range] is replaced with the range you pick, \n[item] with the item link, \n[time] with seconds in countdown."] = true,
		[" Please enter the value of the item."] = true,
		["Value: "] = true,
	}
end)

